# Literature

This chapter contains a table of the titles, authors, abstracts, and DOIs for each indexed publication included in the analysis, and are organized by publication date. Formal citations are included at the end of this document, and in the References section of this volume.

## Works included in analysis

### [@RN20926]

Scopus
EXPORT DATE:06 Apr 2020

Dhoop, T., Stark, S., Olaberria, J.-P., Whitewright, J.
56515481500;57215840055;55641745300;20435130200;
Quantifying Ship Shape in Archaeology: Evaluating 3D Geometric Morphometrics
(2020) International Journal of Nautical Archaeology, . 
https://www.scopus.com/inward/record.uri?eid=2-s2.0-85082033041&doi=10.1111%2f1095-9270.12413&partnerID=40&md5=71cffe70f1c3e522dcfd3aceda41cb5f

DOI: 10.1111/1095-9270.12413

AFFILIATIONS: Centre for Maritime Archaeology, Department of Archaeology, University of Southampton, Highfield, Southampton SO17 1BF, United Kingdom

ABSTRACT: The analysis of the archaeological remains of ships and boats, in particular hull shapes, have been central to wider analysis of performance, function, and significance within past societies. This article reviews established methods of quantifying shape in ship and boat archaeology—linear measurement ratios and form coefficients—and evaluates the utility of 3D geometric morphometrics (GM). The 3D shape of 30 vessels from north-west Europe dating between 325 BC and AD 1915 are quantified to study how hull shape relates to a vessel's function and intended operating environment. A comparison of the three methods highlights the importance of analysing the complexity of a hull in a holistic manner and demonstrates that 3D GM outperforms the traditional methods. © 2020 The Authors. International Journal of Nautical Archaeology © 2020 The Nautical Archaeology Society.

AUTHOR KEYWORDS: geometric morphometrics;  hull shape variation;  Ships

DOCUMENT TYPE: Article

PUBLICATION STAGE: Article in Press

SOURCE: Scopus

### [@RN20927]

Scopus
EXPORT DATE:06 Apr 2020

Ameen, C., Feuerborn, T.R., Brown, S.K., Linderholm, A., Hulme-Beaman, A., Lebrasseur, O., Sinding, M.-H.S., Lounsberry, Z.T., Lin, A.T., Appelt, M., Bachmann, L., Betts, M., Britton, K., Darwent, J., Dietz, R., Fredholm, M., Gopalakrishnan, S., Goriunova, O.I., Grønnow, B., Haile, J., Hallsson, J.H., Harrison, R., Heide-Jørgensen, M.P., Knecht, R., Losey, R.J., Masson-MacLean, E., McGovern, T.H., McManus-Fry, E., Meldgaard, M., Midtdal, Å., Moss, M.L., Nikitin, I.G., Nomokonova, T., Pálsdóttir, A.H., Perri, A., Popov, A.N., Rankin, L., Reuther, J.D., Sablin, M., Schmidt, A.L., Shirar, S., Smiarowski, K., Sonne, C., Stiner, M.C., Vasyukov, M., West, C.F., Ween, G.B., Wennerberg, S.E., Wiig, Ø., Woollett, J., Dalén, L., Hansen, A.J., Gilbert, M.T.P., Sacks, B.N., Frantz, L., Larson, G., Dobney, K., Darwent, C.M., Evin, A.
57190193977;57197822765;7501416848;24399317900;36627224600;52563899200;55336658000;36158513600;57210856507;56366372300;56516348200;8979372900;36027962100;6506853914;7203003549;7003481985;12239105800;6507700864;24450187900;56875784900;6506402159;37069448000;55944048100;7005085911;6602417931;57192264654;7005863479;57188993640;36834995200;57212006066;7201428977;57212007258;23470010200;55899350900;56646131200;57212006327;57213941250;9632715200;6507924182;57212006236;57195889323;37069651200;8759440300;6603814686;57212010185;35079911800;55115729500;56610212700;8442088400;6603018629;6602841361;7401928605;57203214424;7004432277;55470973700;8280762100;6602595568;6503886981;23977570900;
Specialized sledge dogs accompanied Inuit dispersal across the North American Arctic
(2019) Proceedings of the Royal Society B: Biological Sciences, 286 (1916), art. no. 20191929, . 
https://www.scopus.com/inward/record.uri?eid=2-s2.0-85075658594&doi=10.1098%2frspb.2019.1929&partnerID=40&md5=6f2abd40d7d3d001a36ac2d3f797ed93

DOI: 10.1098/rspb.2019.1929

AFFILIATIONS: Department of Archaeology, University of Exeter, Exeter, Devon, United Kingdom; 
Department of Archaeology Classics and Egyptology, University of Liverpool, Liverpool, Merseyside, United Kingdom; 
Department of Archaeology and Classical Studies, Stockholm University, Stockholm, Sweden; 
Centre for GeoGenetics, GLOBE Institute, University of Copenhagen, Copenhagen, Denmark; 
Section for Evolutionary Genomics, GLOBE Institute, University of Copenhagen, Copenhagen, Denmark; 
Qimmeq Project, University of Greenland, Nuussuaq, Greenland; 
Department of Bioinformatics and Genetics, Swedish Museum of Natural History, Stockholm, Sweden; 
Centre for Palaeogenetics, Stockholm, Sweden; 
Department of Anthropology, University of California Davis, Davis, CA, United States; 
Department of Population Health and Reproduction, University of California Davis, Davis, CA, United States; 
Mammalian Ecology and Conservation Unit, Veterinary Genetics Laboratory, University of California Davis, Davis, CA, United States; 
Washington Department of Fish and Wildlife, Olympia, WA, United States; 
Department of Anthropology, Texas AandM University, College Station, TX, United States; 
Palaeogenomics and Bio-archaeology Research Network, Research Laboratory for Archaeology and History of Art, University of Oxford, Oxford, United Kingdom; 
School of Archaeology, University of Oxford, Oxford, United Kingdom; 
Department of Zoology, University of Oxford, Oxford, United Kingdom; 
School of Natural Sciences and Psychology, Liverpool John Moores University, Liverpool, United Kingdom; 
GCRF One Health Regional Network for the Horn of Africa (HORN) Project, Institute of Infection and Global Health, Liverpool, United Kingdom; 
Department of Veterinary and Animal Sciences, University of Oslo, Oslo, Norway; 
Natural History Museum, University of Oslo, Oslo, Norway; 
Centre for Ecological and Evolutionary Synthesis (CEES), Department of Biosciences, University of Oslo, Oslo, Norway; 
University of Oslo Museum of Cultural History, Oslo, Norway; 
Greenland Institute of Natural Resources, Nuuk, Greenland; 
National Museum of Denmark, Copenhagen, Denmark; 
Canadian Museum of History, Gatineau, QC, Canada; 
Department of Anthropology, University of New Brunswick, Fredericton, NB, Canada; 
Department of Archaeology, University of Aberdeen, Aberdeen, United Kingdom; 
Department of Human Evolution, Max Planck Institute for Evolutionary Anthropology, Leipzig, Sachsen, Germany; 
Arctic Research Centre, Aarhus Universitet, Aarhus, Denmark; 
Department of Bioscience, Aarhus Universitet, Aarhus, Denmark; 
Department of Bioscience Roskilde, Aarhus Universitet, Roskilde, Denmark; 
Laboratory of Archaeology and Paleoecology of the Institute, Archaeology and Ethnography (Siberian Branch of Russian Academy of Science), Irkutsk, Russian Federation; 
Faculty of Agricultural and Environmental Sciences, Agricultural University of Iceland, Reykjavik, Iceland; 
Department of Archaeology, History, Cultural Studies, and Religion, University of Bergen, Bergen, Hordaland, Norway; 
Birds and Mammals, Greenland Institute of Natural Resources, Copenhagen K, Denmark; 
Department of Anthropology, University of Alberta, Edmonton, AB, Canada; 
Department of Anthropology, Hunter College CUNY, New York, NY, United States; 
Graduate Center, City University of New York, New York, NY, United States; 
Holmenkollen Ski Museum, Oslo, Norway; 
Department of Anthropology, University of Oregon, Eugene, OR, United States; 
Museum of Archaeology and Ethnography, Inst. of Hist. Archaeo. and Ethnogr. of the Peoples of the Far E. (Far E. Br. of Russ. Acad. of Sci.), Vladivostok, Russian Federation; 
Department of Archaeology and Anthropology, University of Saskatchewan, Saskatoon, SK, Canada; 
Department of Archaeology, Durham University, Durham, United Kingdom; 
Department of Archaeology, Memorial University of Newfoundland, St John's, Canada; 
Department of Anthropology, University of AlaskaMuseum of the North, Fairbanks, AK, United States; 
Zoological Institute of Russian Academy of Sciences, St Petersburg, Russian Federation; 
Section for Cultural Heritage Management, Department of Cultural History, University Museum of Bergen, Bergen, Norway; 
School of Forestry, Henan Agricultural University, Zhengzhou, China; 
School of Anthropology, University of Arizona, Tucson, AZ, United States; 
Department of Biological Diversity and Sustainable Use of Biological Resources, Russian Academy of Sciences, Moskow, Russian Federation; 
Department of Anthropology and Archaeology Program, Boston University, Boston, MA, United States; 
Government of Greenland, Veterinary and Food Authority, Nuuk, Greenland; 
Département des Sciences Historiques, Université Laval, Quebec, Canada; 
Norwegian University of Science and Technology, University Museum, Trondheim, Norway; 
School of Biological and Chemical Sciences, Queen Mary University of London, London, United Kingdom; 
Department of Archaeology, Simon Fraser University, Burnaby, BC, Canada; 
Institut des Sciences de l'Evolution-Montpellier, CNRS, Université de Montpellier, IRD, EPHE, Montpellier, Occitanie, France

ABSTRACT: Domestic dogs have been central to life in the North American Arctic for millennia. The ancestors of the Inuit were the first to introduce the widespread usage of dog sledge transportation technology to the Americas, but whether the Inuit adopted local Palaeo-Inuit dogs or introduced a new dog population to the region remains unknown. To test these hypotheses, we generated mitochondrial DNA and geometric morphometric data of skull and dental elements from a total of 922 North American Arctic dogs and wolves spanning over 4500 years. Our analyses revealed that dogs from Inuit sites dating from2000 BP possess morphological and genetic signatures that distinguish them from earlier Palaeo-Inuit dogs, and identified a novel mitochondrial clade in eastern Siberia and Alaska. The genetic legacy of these Inuit dogs survives today in modern Arctic sledge dogs despite phenotypic differences between archaeological and modern Arctic dogs. Together, our data reveal that Inuit dogs derive from a secondary pre-contact migration of dogs distinct from Palaeo-Inuit dogs, and probably aided the Inuit expansion across the North American Arctic beginning around 1000 BP. © 2019 The Author(s) Published by the Royal Society.

AUTHOR KEYWORDS: Ancient DNA;  Archaeology;  Canis lupus familiaris;  Circumpolar;  Geometric morphometrics;  Migration

DOCUMENT TYPE: Article

PUBLICATION STAGE: Final

ACCESS TYPE: Open Access

SOURCE: Scopus

### [@RN20928]

Scopus
EXPORT DATE:06 Apr 2020

Ciarlo, N.C., Charlin, J., Alberti, J., Buscaglia, S., Vivar Lombarte, G., Geli Mauri, R.
35794959100;26658892500;55545364700;37083202300;57000506700;57000414000;
Size and shape analysis of gunflints from the British shipwreck Deltebre I (1813), Catalonia, Spain: a geometric morphometric comparison of unused and used artefacts
(2019) Archaeological and Anthropological Sciences, 11 (12), pp. 6569-6582. 
https://www.scopus.com/inward/record.uri?eid=2-s2.0-85073772794&doi=10.1007%2fs12520-019-00925-1&partnerID=40&md5=0c5beb733a00e7bf778447fdecada6c1

DOI: 10.1007/s12520-019-00925-1

AFFILIATIONS: National Scientific and Technical Research Council (Consejo Nacional de Investigaciones Científicas y Técnicas - CONICET), Buenos Aires, Argentina; 
Institute of Archaeology, School of Philosophy & Liberal Arts, University of Buenos Aires (Instituto de Arqueología, Facultad de Filosofía y Letras, Universidad de Buenos Aires), Buenos Aires, Argentina; 
Multidisciplinary Institute of History and Human Sciences of CONICET (Instituto Multidisciplinario de Historia y Ciencias Humanas - IMHICIHU-CONICET), Buenos Aires, Argentina; 
School of Philosophy & Liberal Arts, University of Buenos Aires (Facultad de Filosofía y Letras, Universidad de Buenos Aires), Buenos Aires, Argentina; 
Centre for Underwater Archaeology of Catalonia, Archaeological Museum of Catalonia (Centre d’Arqueologia Subaquàtica de Catalunya, Museu d’Arqueologia de Catalunya - CASC-MAC), Girona, Spain

ABSTRACT: Gunflints represent a worldwide feature of lithic technology in modern times. This type of artefact was used to ignite the powder of firearms through a flintlock mechanism from the middle-seventeenth to the early-twentieth century in different contexts around the world. Taking what is a novel and exploratory approach in historical archaeology, this paper offers a quantitative analysis of a random sample of 200 unused gunflints recovered from the British shipwreck Deltebre I. This cargo ship belonged to an allied convoy that unsuccessfully tried to liberate Tarragona city from the Napoleonic forces, and sunk in the Ebro river delta, Catalonia, Spain, in 1813. The results from size and shape characterisation of the unused gunflints using geometric morphometric methods are presented. In order to assess morphometric variation between used and unused artefacts, this sample was compared with published images of 22 used British gunflints from different archaeological contexts. Finally, the usefulness of applied methodology to quantitatively characterise the design and morphometric variations of this kind of artefacts is highlighted. © 2019, Springer-Verlag GmbH Germany, part of Springer Nature.

AUTHOR KEYWORDS: Geometric morphometrics;  Mass-production characterisation;  Nineteenth century shipwreck;  Size and shape variations;  Unused and used gunflints

DOCUMENT TYPE: Article

PUBLICATION STAGE: Final

SOURCE: Scopus

### [@RN20929]

Scopus
EXPORT DATE:06 Apr 2020

Stoetzel, E., Lalis, A., Nicolas, V., Aulagnier, S., Benazzou, T., Dauphin, Y., El Hajraoui, M.A., El Hassani, A., Fahd, S., Fekhaoui, M., Geigl, E.-M., Lapointe, F.-J., Leblois, R., Ohler, A., Nespoulet, R., Denys, C.
23111731600;15136229600;14825723800;6701362924;6602545717;7006470205;24168312900;6701774532;6507696424;6508193459;6602182148;7003540226;6602486136;6603965396;23110649000;7006755120;
Quaternary terrestrial microvertebrates from mediterranean northwestern Africa: State-of-the-art focused on recent multidisciplinary studies
(2019) Quaternary Science Reviews, 224, art. no. 105966, . Cited 1 time.
https://www.scopus.com/inward/record.uri?eid=2-s2.0-85073012268&doi=10.1016%2fj.quascirev.2019.105966&partnerID=40&md5=5e82395a70da2c8ce7799749e0f41b7f

DOI: 10.1016/j.quascirev.2019.105966

AFFILIATIONS: Histoire Naturelle de l'Homme Préhistorique (HNHP), UMR 7194, Muséum National d'Histoire Naturelle, CNRS, Sorbonne Universités, UPVD, Paris, France; 
Institut de Systématique, Evolution, Biodiversité (ISYEB), UMR 7205, Muséum National d'Histoire Naturelle, CNRS, Sorbonne Universités, EPHE, Université des Antilles, Paris, France; 
Comportement et Ecologie de la Faune Sauvage, INRA, Castanet Tolosan, France; 
Faculty of Sciences, Mohammed V University, Rabat, Morocco; 
Institut National des Sciences de l'Archéologie et du Patrimoine (INSAP), Rabat, Morocco; 
Institut Scientifique, Mohammed V University, Rabat, Morocco; 
Faculté des Sciences de Tétouan, Université Abdelmalek Essaâdi, Tétouan, Morocco; 
Institut Jacques Monod, Equipe Epigénome et Paléogénome, Paris, France; 
Département de Sciences Biologiques, Université de Montréal, Québec, Canada; 
Centre de Biologie pour la Gestion des Populations (CBGP), UMR 1062, INRAMontferrier-sur-Lez, France

ABSTRACT: Northwestern Africa is today characterized by high geographical, climatic and ecological diversity; it is recognized as a hotspot of biodiversity and a major area for both human and faunal evolution. Studies of North African fossil microvertebrates have increased considerably in recent years, but they no longer just provide palaeontological descriptions of the species found in the assemblages. They also aim at better understanding the evolution of faunal communities in relation to Quaternary climate changes and at reconstructing the palaeoenvironmental background of prehistoric human occupations, in well-established taphonomic and chronological contexts. These studies are also increasingly adopting an integrative approach by combining archaeology, palaeontology, (palaeo)genetics, taphonomy, palaeoecology and systematics, and using new methods such as geometric morphometrics and isotopic analyses on both fossil and modern specimens. This paper aims to present a history of the studies on Quaternary terrestrial microvertebrates from northwestern Africa, and show how recent multidisciplinary studies have provided new perspectives and evidence on the respective influences of climate change and increasing human pressure on their evolution. © 2019 Elsevier Ltd

AUTHOR KEYWORDS: Herpetofauna;  Integrative approach;  Maghreb;  Micromammals

DOCUMENT TYPE: Article

PUBLICATION STAGE: Final

SOURCE: Scopus

### [@RN20930]

Scopus
EXPORT DATE:06 Apr 2020

Natahi, S., Coquerelle, M., Pereira, G., Bayle, P.
57210429853;36140239700;36192143700;35434353800;
Neurocranial shape variation among Tarascan populations: Evidence for varying degrees in artificially modified crania in pre-Hispanic West Mexico (1200–1400 AD)
(2019) American Journal of Physical Anthropology, 170 (3), pp. 418-432. 
https://www.scopus.com/inward/record.uri?eid=2-s2.0-85070705630&doi=10.1002%2fajpa.23917&partnerID=40&md5=9848cacbc1a4f7470334281e873f0428

DOI: 10.1002/ajpa.23917

AFFILIATIONS: Université de Bordeaux, CNRS, MCC, UMR 5199 PACEA, Pessac, France; 
Department of Medicine and Surgery (Stomatology Area), Universidad Rey Juan Carlos, Alcorcón, Spain; 
UMR 8096, Archéologie des Amériques, CNRS, Maison René-Ginouvès, Nanterre, France

ABSTRACT: Introduction: Along the Mesoamerican western margin, the Zacapu basin has yielded a large number of human remains demonstrating usage of artificial cranial modification (ACM). However, at the onset of the Middle Postclassic (1200–1400 AD) only few individuals still exhibit clear signs of ACM. Some authors have suggested that, rather than disappearing entirely, ACM may have become less visible anatomically, making it difficult to identify based on simple visual analyses. Here, we used 3D geometric morphometric methods to investigate the extent to which ACM persisted during the Postclassic in this region. Materials and methods: We measured the 3D vault's shape changes in a sample of surface-scanned human crania: 55 individuals from the Postclassic Zacapu basin and a control group of 31 individuals from a Huichol Mexican Indian sample and a French medieval series from La Granède. We used a principal component analysis to explore the shape variation within the sample and employed the neighbor joining method to identify morphological groups. Finally, we quantified each individual's asymmetry. Results: We identified three groups displaying shape features diverging from those of the control group. The first group is characterized by marked fronto-obelionic ACM, whereas the other two show mild forms of ACM. The individuals in all three groups display moderate to high degrees of asymmetry compared to the control group. Discussion: The marked fronto-obelionic modification is clear evidence of a specific ACM technique. The two types of mild ACM most likely result from different techniques but their moderate degree of modification brings into question the intentions behind their production. © 2019 Wiley Periodicals, Inc.

AUTHOR KEYWORDS: 3D geometric morphometrics;  artificial cranial modification;  asymmetry;  Mesoamerican Archaeology

DOCUMENT TYPE: Article

PUBLICATION STAGE: Final

SOURCE: Scopus

